config/routes.rb
Rails.application.routes.draw do
  
  root 'thres#index'
  resources :thres
  resources :thres do
    resources :comments, only: [:create, :destroy]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :thre
    
    validates :thre, presence: true
    validates :name, presence: true
    validates :content, presence: true, length: { in: 1..1000 }
end

app/models/thre.rb
class Thre < ApplicationRecord
    has_many :comments, dependent: :destroy
    
    validates :title, presence: true, length: { in: 4..127 }
    validates :editor, presence: true, length: { in: 1..30 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    
    def create
        @thre = Thre.find(params[:thre_id])
        @comment = Comment.new(params_comment)
        @comment.thre = @thre
        
        if @comment.save
            redirect_to thre_url(@thre)
        else
            render "thres/show"
        end
    end
    
    def destroy
        @thre = Thre.find(params[:thre_id])
        @comment = Comment.find(params[:id])
        @comment.destroy
        redirect_to thre_url(@thre)
    end
    
    private
    
    def params_comment
        params.require(:comment).permit(:name, :content)
    end
    
end

app/controllers/thres_controller.rb
class ThresController < ApplicationController
  before_action :set_thre, only: [:show, :edit, :update, :destroy]

  # GET /thres
  # GET /thres.json
  def index
    @thres = Thre.all
  end

  # GET /thres/1
  # GET /thres/1.json
  def show
    @comment = Comment.new
  end

  # GET /thres/new
  def new
    @thre = Thre.new
  end

  # GET /thres/1/edit
  def edit
  end

  # POST /thres
  # POST /thres.json
  def create
    @thre = Thre.new(thre_params)

    respond_to do |format|
      if @thre.save
        format.html { redirect_to @thre, notice: 'Thre was successfully created.' }
        format.json { render :show, status: :created, location: @thre }
      else
        format.html { render :new }
        format.json { render json: @thre.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /thres/1
  # PATCH/PUT /thres/1.json
  def update
    respond_to do |format|
      if @thre.update(thre_params)
        format.html { redirect_to @thre, notice: 'Thre was successfully updated.' }
        format.json { render :show, status: :ok, location: @thre }
      else
        format.html { render :edit }
        format.json { render json: @thre.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /thres/1
  # DELETE /thres/1.json
  def destroy
    @thre.destroy
    respond_to do |format|
      format.html { redirect_to thres_url, notice: 'Thre was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_thre
      @thre = Thre.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def thre_params
      params.require(:thre).permit(:title, :editor)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/thres_helper.rb
module ThresHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Nityanni</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/thres/_form.html.erb
<%= form_for(thre) do |f| %>
  <% if thre.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(thre.errors.count, "error") %> prohibited this thre from being saved:</h2>

      <ul>
      <% thre.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="thre">
  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :editor %>
    <%= f.text_field :editor %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
</div>
<% end %>

app/views/thres/edit.html.erb
<h1>スレッドの編集</h1>

<%= render 'form', thre: @thre %>

<%= link_to 'Show', @thre %> |
<%= link_to 'Back', thres_path %>

app/views/thres/index.html.erb
<p id="notice"><%= notice %></p>

<div class="thre">
  <img src="<%= asset_path "thre.png" %>" />

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Editor</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @thres.each do |thre| %>
      <tr>
        <td><%= thre.title %></td>
        <td><%= thre.editor %></td>
        <td><%= thre.created_at.to_formatted_s(:extra_short) %></td>
        <td><%= link_to 'Show', thre %></td>
        <td><%= link_to 'Edit', edit_thre_path(thre) %></td>
        <td><%= link_to 'Destroy', thre, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
  </table>

<br>

<%= link_to 'スレッドの新規作成', new_thre_path %>

</div>

app/views/thres/new.html.erb
<h1>新規スレッド</h1>

<%= render 'form', thre: @thre %>

<%= link_to 'Back', thres_path %>

app/views/thres/show.html.erb
<p id="notice"><%= notice %></p>

<div class="thre">
<p class="thre-show-title">
  <strong class="thre-show"><%= @thre.title %></strong>
</p>

<%= link_to 'タイトルの編集', edit_thre_path(@thre) %> |
<%= link_to '戻る', thres_path %>
<br>
<br>
<% @thre.comments.each do |comment| %>
名前：<strong><%= comment.name %></strong>
投稿日：<%= comment.created_at.to_formatted_s(:extra_short) %><br>
<%= comment.content %>
<%= link_to "削除する", thre_comment_path(@thre, comment), method: :delete, data: { confirm: "本当に削除しますか?" } %> <br>
<% end %>

<%= form_for @comment, url: thre_comments_path(@thre, @comment) do |f| %>
  <p class="thre-show-comment-f">
  名前：<%= f.text_field :name %>｜
  コメント：  <%= f.text_area :content %><br>
  </p>
  <br>
  <%= f.submit %>
<% end %>
</div>